# Generated by Django 2.2.16 on 2020-10-09 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=1000)),
                ('density_min', models.DecimalField(decimal_places=3, max_digits=5)),
                ('density_max', models.DecimalField(decimal_places=3, max_digits=5)),
                ('specific_gravity_min', models.DecimalField(decimal_places=3, max_digits=5)),
                ('specific_gravity_max', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('food', models.OneToOneField(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='food.Food')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('foods', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='food.Food')),
            ],
        ),
    ]
